package com.daming.bartersystem.entitys;

import java.util.ArrayList;
import java.util.List;

public class BarterOrderItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public BarterOrderItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderitemIdIsNull() {
            addCriterion("orderitem_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdIsNotNull() {
            addCriterion("orderitem_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdEqualTo(Integer value) {
            addCriterion("orderitem_id =", value, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdNotEqualTo(Integer value) {
            addCriterion("orderitem_id <>", value, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdGreaterThan(Integer value) {
            addCriterion("orderitem_id >", value, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderitem_id >=", value, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdLessThan(Integer value) {
            addCriterion("orderitem_id <", value, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdLessThanOrEqualTo(Integer value) {
            addCriterion("orderitem_id <=", value, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdIn(List<Integer> values) {
            addCriterion("orderitem_id in", values, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdNotIn(List<Integer> values) {
            addCriterion("orderitem_id not in", values, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdBetween(Integer value1, Integer value2) {
            addCriterion("orderitem_id between", value1, value2, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderitemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("orderitem_id not between", value1, value2, "orderitemId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUid1IsNull() {
            addCriterion("uid1 is null");
            return (Criteria) this;
        }

        public Criteria andUid1IsNotNull() {
            addCriterion("uid1 is not null");
            return (Criteria) this;
        }

        public Criteria andUid1EqualTo(Integer value) {
            addCriterion("uid1 =", value, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1NotEqualTo(Integer value) {
            addCriterion("uid1 <>", value, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1GreaterThan(Integer value) {
            addCriterion("uid1 >", value, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1GreaterThanOrEqualTo(Integer value) {
            addCriterion("uid1 >=", value, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1LessThan(Integer value) {
            addCriterion("uid1 <", value, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1LessThanOrEqualTo(Integer value) {
            addCriterion("uid1 <=", value, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1In(List<Integer> values) {
            addCriterion("uid1 in", values, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1NotIn(List<Integer> values) {
            addCriterion("uid1 not in", values, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1Between(Integer value1, Integer value2) {
            addCriterion("uid1 between", value1, value2, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid1NotBetween(Integer value1, Integer value2) {
            addCriterion("uid1 not between", value1, value2, "uid1");
            return (Criteria) this;
        }

        public Criteria andUid2IsNull() {
            addCriterion("uid2 is null");
            return (Criteria) this;
        }

        public Criteria andUid2IsNotNull() {
            addCriterion("uid2 is not null");
            return (Criteria) this;
        }

        public Criteria andUid2EqualTo(Integer value) {
            addCriterion("uid2 =", value, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2NotEqualTo(Integer value) {
            addCriterion("uid2 <>", value, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2GreaterThan(Integer value) {
            addCriterion("uid2 >", value, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2GreaterThanOrEqualTo(Integer value) {
            addCriterion("uid2 >=", value, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2LessThan(Integer value) {
            addCriterion("uid2 <", value, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2LessThanOrEqualTo(Integer value) {
            addCriterion("uid2 <=", value, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2In(List<Integer> values) {
            addCriterion("uid2 in", values, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2NotIn(List<Integer> values) {
            addCriterion("uid2 not in", values, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2Between(Integer value1, Integer value2) {
            addCriterion("uid2 between", value1, value2, "uid2");
            return (Criteria) this;
        }

        public Criteria andUid2NotBetween(Integer value1, Integer value2) {
            addCriterion("uid2 not between", value1, value2, "uid2");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressIsNull() {
            addCriterion("receiver_address is null");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressIsNotNull() {
            addCriterion("receiver_address is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressEqualTo(String value) {
            addCriterion("receiver_address =", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotEqualTo(String value) {
            addCriterion("receiver_address <>", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressGreaterThan(String value) {
            addCriterion("receiver_address >", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressGreaterThanOrEqualTo(String value) {
            addCriterion("receiver_address >=", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressLessThan(String value) {
            addCriterion("receiver_address <", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressLessThanOrEqualTo(String value) {
            addCriterion("receiver_address <=", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressLike(String value) {
            addCriterion("receiver_address like", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotLike(String value) {
            addCriterion("receiver_address not like", value, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressIn(List<String> values) {
            addCriterion("receiver_address in", values, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotIn(List<String> values) {
            addCriterion("receiver_address not in", values, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressBetween(String value1, String value2) {
            addCriterion("receiver_address between", value1, value2, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andReceiverAddressNotBetween(String value1, String value2) {
            addCriterion("receiver_address not between", value1, value2, "receiverAddress");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateIsNull() {
            addCriterion("order_item_state is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateIsNotNull() {
            addCriterion("order_item_state is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateEqualTo(Integer value) {
            addCriterion("order_item_state =", value, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateNotEqualTo(Integer value) {
            addCriterion("order_item_state <>", value, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateGreaterThan(Integer value) {
            addCriterion("order_item_state >", value, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_item_state >=", value, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateLessThan(Integer value) {
            addCriterion("order_item_state <", value, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateLessThanOrEqualTo(Integer value) {
            addCriterion("order_item_state <=", value, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateIn(List<Integer> values) {
            addCriterion("order_item_state in", values, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateNotIn(List<Integer> values) {
            addCriterion("order_item_state not in", values, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateBetween(Integer value1, Integer value2) {
            addCriterion("order_item_state between", value1, value2, "orderItemState");
            return (Criteria) this;
        }

        public Criteria andOrderItemStateNotBetween(Integer value1, Integer value2) {
            addCriterion("order_item_state not between", value1, value2, "orderItemState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table barter_order_item
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}