package com.daming.bartersystem.entitys;

public class BarterOrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order_item.orderitem_id
     *
     * @mbg.generated
     */
    private Integer orderitemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order_item.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order_item.uid1
     *
     * @mbg.generated
     */
    private Integer uid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order_item.uid2
     *
     * @mbg.generated
     */
    private Integer uid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order_item.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order_item.receiver_address
     *
     * @mbg.generated
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order_item.order_item_state
     *
     * @mbg.generated
     */
    private Integer orderItemState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order_item.orderitem_id
     *
     * @return the value of barter_order_item.orderitem_id
     *
     * @mbg.generated
     */
    public Integer getOrderitemId() {
        return orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order_item.orderitem_id
     *
     * @param orderitemId the value for barter_order_item.orderitem_id
     *
     * @mbg.generated
     */
    public void setOrderitemId(Integer orderitemId) {
        this.orderitemId = orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order_item.order_id
     *
     * @return the value of barter_order_item.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order_item.order_id
     *
     * @param orderId the value for barter_order_item.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order_item.uid1
     *
     * @return the value of barter_order_item.uid1
     *
     * @mbg.generated
     */
    public Integer getUid1() {
        return uid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order_item.uid1
     *
     * @param uid1 the value for barter_order_item.uid1
     *
     * @mbg.generated
     */
    public void setUid1(Integer uid1) {
        this.uid1 = uid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order_item.uid2
     *
     * @return the value of barter_order_item.uid2
     *
     * @mbg.generated
     */
    public Integer getUid2() {
        return uid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order_item.uid2
     *
     * @param uid2 the value for barter_order_item.uid2
     *
     * @mbg.generated
     */
    public void setUid2(Integer uid2) {
        this.uid2 = uid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order_item.item_id
     *
     * @return the value of barter_order_item.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order_item.item_id
     *
     * @param itemId the value for barter_order_item.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order_item.receiver_address
     *
     * @return the value of barter_order_item.receiver_address
     *
     * @mbg.generated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order_item.receiver_address
     *
     * @param receiverAddress the value for barter_order_item.receiver_address
     *
     * @mbg.generated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order_item.order_item_state
     *
     * @return the value of barter_order_item.order_item_state
     *
     * @mbg.generated
     */
    public Integer getOrderItemState() {
        return orderItemState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order_item.order_item_state
     *
     * @param orderItemState the value for barter_order_item.order_item_state
     *
     * @mbg.generated
     */
    public void setOrderItemState(Integer orderItemState) {
        this.orderItemState = orderItemState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BarterOrderItem other = (BarterOrderItem) that;
        return (this.getOrderitemId() == null ? other.getOrderitemId() == null : this.getOrderitemId().equals(other.getOrderitemId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getUid1() == null ? other.getUid1() == null : this.getUid1().equals(other.getUid1()))
            && (this.getUid2() == null ? other.getUid2() == null : this.getUid2().equals(other.getUid2()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getReceiverAddress() == null ? other.getReceiverAddress() == null : this.getReceiverAddress().equals(other.getReceiverAddress()))
            && (this.getOrderItemState() == null ? other.getOrderItemState() == null : this.getOrderItemState().equals(other.getOrderItemState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderitemId() == null) ? 0 : getOrderitemId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getUid1() == null) ? 0 : getUid1().hashCode());
        result = prime * result + ((getUid2() == null) ? 0 : getUid2().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getReceiverAddress() == null) ? 0 : getReceiverAddress().hashCode());
        result = prime * result + ((getOrderItemState() == null) ? 0 : getOrderItemState().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "BarterOrderItem{" +
                "orderitemId=" + orderitemId +
                ", orderId=" + orderId +
                ", uid1=" + uid1 +
                ", uid2=" + uid2 +
                ", itemId=" + itemId +
                ", receiverAddress='" + receiverAddress + '\'' +
                ", orderItemState=" + orderItemState +
                '}';
    }
}