package com.daming.bartersystem.entitys;

import java.util.Date;

public class BarterOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order.barter_order_id
     *
     * @mbg.generated
     */
    private Integer barterOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column barter_order.order_state
     *
     * @mbg.generated
     */
    private Integer orderState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order.barter_order_id
     *
     * @return the value of barter_order.barter_order_id
     *
     * @mbg.generated
     */
    public Integer getBarterOrderId() {
        return barterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order.barter_order_id
     *
     * @param barterOrderId the value for barter_order.barter_order_id
     *
     * @mbg.generated
     */
    public void setBarterOrderId(Integer barterOrderId) {
        this.barterOrderId = barterOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order.create_time
     *
     * @return the value of barter_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order.create_time
     *
     * @param createTime the value for barter_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order.end_time
     *
     * @return the value of barter_order.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order.end_time
     *
     * @param endTime the value for barter_order.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column barter_order.order_state
     *
     * @return the value of barter_order.order_state
     *
     * @mbg.generated
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column barter_order.order_state
     *
     * @param orderState the value for barter_order.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BarterOrder other = (BarterOrder) that;
        return (this.getBarterOrderId() == null ? other.getBarterOrderId() == null : this.getBarterOrderId().equals(other.getBarterOrderId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getOrderState() == null ? other.getOrderState() == null : this.getOrderState().equals(other.getOrderState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBarterOrderId() == null) ? 0 : getBarterOrderId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getOrderState() == null) ? 0 : getOrderState().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "BarterOrder{" +
                "barterOrderId=" + barterOrderId +
                ", createTime=" + createTime +
                ", endTime=" + endTime +
                ", orderState=" + orderState +
                '}';
    }
}