package com.daming.bartersystem.entitys;

public class Classification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification_id
     *
     * @mbg.generated
     */
    private Integer classificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.classification
     *
     * @mbg.generated
     */
    private String classification;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification_id
     *
     * @return the value of classification.classification_id
     *
     * @mbg.generated
     */
    public Integer getClassificationId() {
        return classificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification_id
     *
     * @param classificationId the value for classification.classification_id
     *
     * @mbg.generated
     */
    public void setClassificationId(Integer classificationId) {
        this.classificationId = classificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.classification
     *
     * @return the value of classification.classification
     *
     * @mbg.generated
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.classification
     *
     * @param classification the value for classification.classification
     *
     * @mbg.generated
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Classification other = (Classification) that;
        return (this.getClassificationId() == null ? other.getClassificationId() == null : this.getClassificationId().equals(other.getClassificationId()))
            && (this.getClassification() == null ? other.getClassification() == null : this.getClassification().equals(other.getClassification()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getClassificationId() == null) ? 0 : getClassificationId().hashCode());
        result = prime * result + ((getClassification() == null) ? 0 : getClassification().hashCode());
        return result;
    }
}