package com.daming.bartersystem.entitys;

import java.math.BigDecimal;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.ship_address
     *
     * @mbg.generated
     */
    private String shipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.ref_price
     *
     * @mbg.generated
     */
    private BigDecimal refPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.classification_id
     *
     * @mbg.generated
     */
    private Integer classificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.isOn
     *
     * @mbg.generated
     */
    private Integer ison;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_id
     *
     * @return the value of item.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_id
     *
     * @param itemId the value for item.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.uid
     *
     * @return the value of item.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.uid
     *
     * @param uid the value for item.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.title
     *
     * @return the value of item.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.title
     *
     * @param title the value for item.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.ship_address
     *
     * @return the value of item.ship_address
     *
     * @mbg.generated
     */
    public String getShipAddress() {
        return shipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.ship_address
     *
     * @param shipAddress the value for item.ship_address
     *
     * @mbg.generated
     */
    public void setShipAddress(String shipAddress) {
        this.shipAddress = shipAddress == null ? null : shipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.ref_price
     *
     * @return the value of item.ref_price
     *
     * @mbg.generated
     */
    public BigDecimal getRefPrice() {
        return refPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.ref_price
     *
     * @param refPrice the value for item.ref_price
     *
     * @mbg.generated
     */
    public void setRefPrice(BigDecimal refPrice) {
        this.refPrice = refPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.classification_id
     *
     * @return the value of item.classification_id
     *
     * @mbg.generated
     */
    public Integer getClassificationId() {
        return classificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.classification_id
     *
     * @param classificationId the value for item.classification_id
     *
     * @mbg.generated
     */
    public void setClassificationId(Integer classificationId) {
        this.classificationId = classificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.stock
     *
     * @return the value of item.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.stock
     *
     * @param stock the value for item.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.isOn
     *
     * @return the value of item.isOn
     *
     * @mbg.generated
     */
    public Integer getIson() {
        return ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.isOn
     *
     * @param ison the value for item.isOn
     *
     * @mbg.generated
     */
    public void setIson(Integer ison) {
        this.ison = ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.description
     *
     * @return the value of item.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.description
     *
     * @param description the value for item.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Item other = (Item) that;
        return (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getShipAddress() == null ? other.getShipAddress() == null : this.getShipAddress().equals(other.getShipAddress()))
            && (this.getRefPrice() == null ? other.getRefPrice() == null : this.getRefPrice().equals(other.getRefPrice()))
            && (this.getClassificationId() == null ? other.getClassificationId() == null : this.getClassificationId().equals(other.getClassificationId()))
            && (this.getStock() == null ? other.getStock() == null : this.getStock().equals(other.getStock()))
            && (this.getIson() == null ? other.getIson() == null : this.getIson().equals(other.getIson()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getShipAddress() == null) ? 0 : getShipAddress().hashCode());
        result = prime * result + ((getRefPrice() == null) ? 0 : getRefPrice().hashCode());
        result = prime * result + ((getClassificationId() == null) ? 0 : getClassificationId().hashCode());
        result = prime * result + ((getStock() == null) ? 0 : getStock().hashCode());
        result = prime * result + ((getIson() == null) ? 0 : getIson().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "Item{" +
                "itemId=" + itemId +
                ", uid=" + uid +
                ", title='" + title + '\'' +
                ", shipAddress='" + shipAddress + '\'' +
                ", refPrice=" + refPrice +
                ", classificationId=" + classificationId +
                ", stock=" + stock +
                ", ison=" + ison +
                ", description='" + description + '\'' +
                '}';
    }
}