package com.daming.bartersystem.entitys;

public class ShoppingTrolley {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_trolley.trolley_id
     *
     * @mbg.generated
     */
    private Integer trolleyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_trolley.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_trolley.trolley_id
     *
     * @return the value of shopping_trolley.trolley_id
     *
     * @mbg.generated
     */
    public Integer getTrolleyId() {
        return trolleyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_trolley.trolley_id
     *
     * @param trolleyId the value for shopping_trolley.trolley_id
     *
     * @mbg.generated
     */
    public void setTrolleyId(Integer trolleyId) {
        this.trolleyId = trolleyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_trolley.uid
     *
     * @return the value of shopping_trolley.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_trolley.uid
     *
     * @param uid the value for shopping_trolley.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShoppingTrolley other = (ShoppingTrolley) that;
        return (this.getTrolleyId() == null ? other.getTrolleyId() == null : this.getTrolleyId().equals(other.getTrolleyId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTrolleyId() == null) ? 0 : getTrolleyId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        return result;
    }
}