package com.daming.bartersystem.entitys;

public class ShoppingTrolleyItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_trolley_item.trolley_item_id
     *
     * @mbg.generated
     */
    private Integer trolleyItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_trolley_item.trolley_id
     *
     * @mbg.generated
     */
    private Integer trolleyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_trolley_item.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_trolley_item.trolley_item_id
     *
     * @return the value of shopping_trolley_item.trolley_item_id
     *
     * @mbg.generated
     */
    public Integer getTrolleyItemId() {
        return trolleyItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_trolley_item.trolley_item_id
     *
     * @param trolleyItemId the value for shopping_trolley_item.trolley_item_id
     *
     * @mbg.generated
     */
    public void setTrolleyItemId(Integer trolleyItemId) {
        this.trolleyItemId = trolleyItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_trolley_item.trolley_id
     *
     * @return the value of shopping_trolley_item.trolley_id
     *
     * @mbg.generated
     */
    public Integer getTrolleyId() {
        return trolleyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_trolley_item.trolley_id
     *
     * @param trolleyId the value for shopping_trolley_item.trolley_id
     *
     * @mbg.generated
     */
    public void setTrolleyId(Integer trolleyId) {
        this.trolleyId = trolleyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_trolley_item.item_id
     *
     * @return the value of shopping_trolley_item.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_trolley_item.item_id
     *
     * @param itemId the value for shopping_trolley_item.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShoppingTrolleyItem other = (ShoppingTrolleyItem) that;
        return (this.getTrolleyItemId() == null ? other.getTrolleyItemId() == null : this.getTrolleyItemId().equals(other.getTrolleyItemId()))
            && (this.getTrolleyId() == null ? other.getTrolleyId() == null : this.getTrolleyId().equals(other.getTrolleyId()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTrolleyItemId() == null) ? 0 : getTrolleyItemId().hashCode());
        result = prime * result + ((getTrolleyId() == null) ? 0 : getTrolleyId().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        return result;
    }
}