package com.daming.bartersystem.entitys;

import java.util.Date;

public class UserReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_review.user_review_id
     *
     * @mbg.generated
     */
    private Integer userReviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_review.review_father_id
     *
     * @mbg.generated
     */
    private Integer reviewFatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_review.review_son_id
     *
     * @mbg.generated
     */
    private Integer reviewSonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_review.review_time
     *
     * @mbg.generated
     */
    private Date reviewTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_review.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_review.review_content
     *
     * @mbg.generated
     */
    private String reviewContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_review.user_review_id
     *
     * @return the value of user_review.user_review_id
     *
     * @mbg.generated
     */
    public Integer getUserReviewId() {
        return userReviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_review.user_review_id
     *
     * @param userReviewId the value for user_review.user_review_id
     *
     * @mbg.generated
     */
    public void setUserReviewId(Integer userReviewId) {
        this.userReviewId = userReviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_review.review_father_id
     *
     * @return the value of user_review.review_father_id
     *
     * @mbg.generated
     */
    public Integer getReviewFatherId() {
        return reviewFatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_review.review_father_id
     *
     * @param reviewFatherId the value for user_review.review_father_id
     *
     * @mbg.generated
     */
    public void setReviewFatherId(Integer reviewFatherId) {
        this.reviewFatherId = reviewFatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_review.review_son_id
     *
     * @return the value of user_review.review_son_id
     *
     * @mbg.generated
     */
    public Integer getReviewSonId() {
        return reviewSonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_review.review_son_id
     *
     * @param reviewSonId the value for user_review.review_son_id
     *
     * @mbg.generated
     */
    public void setReviewSonId(Integer reviewSonId) {
        this.reviewSonId = reviewSonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_review.review_time
     *
     * @return the value of user_review.review_time
     *
     * @mbg.generated
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_review.review_time
     *
     * @param reviewTime the value for user_review.review_time
     *
     * @mbg.generated
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_review.item_id
     *
     * @return the value of user_review.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_review.item_id
     *
     * @param itemId the value for user_review.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_review.review_content
     *
     * @return the value of user_review.review_content
     *
     * @mbg.generated
     */
    public String getReviewContent() {
        return reviewContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_review.review_content
     *
     * @param reviewContent the value for user_review.review_content
     *
     * @mbg.generated
     */
    public void setReviewContent(String reviewContent) {
        this.reviewContent = reviewContent == null ? null : reviewContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserReview other = (UserReview) that;
        return (this.getUserReviewId() == null ? other.getUserReviewId() == null : this.getUserReviewId().equals(other.getUserReviewId()))
            && (this.getReviewFatherId() == null ? other.getReviewFatherId() == null : this.getReviewFatherId().equals(other.getReviewFatherId()))
            && (this.getReviewSonId() == null ? other.getReviewSonId() == null : this.getReviewSonId().equals(other.getReviewSonId()))
            && (this.getReviewTime() == null ? other.getReviewTime() == null : this.getReviewTime().equals(other.getReviewTime()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getReviewContent() == null ? other.getReviewContent() == null : this.getReviewContent().equals(other.getReviewContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserReviewId() == null) ? 0 : getUserReviewId().hashCode());
        result = prime * result + ((getReviewFatherId() == null) ? 0 : getReviewFatherId().hashCode());
        result = prime * result + ((getReviewSonId() == null) ? 0 : getReviewSonId().hashCode());
        result = prime * result + ((getReviewTime() == null) ? 0 : getReviewTime().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getReviewContent() == null) ? 0 : getReviewContent().hashCode());
        return result;
    }
}