package com.daming.bartersystem.entitys;

public class UserBarterUnformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_barter_information.udi_id
     *
     * @mbg.generated
     */
    private Integer udiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_barter_information.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_barter_information.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_barter_information.consignee_phone
     *
     * @mbg.generated
     */
    private String consigneePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_barter_information.consignee_address
     *
     * @mbg.generated
     */
    private String consigneeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_barter_information.consignee_postalcode
     *
     * @mbg.generated
     */
    private Integer consigneePostalcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_barter_information.udi_id
     *
     * @return the value of user_barter_information.udi_id
     *
     * @mbg.generated
     */
    public Integer getUdiId() {
        return udiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_barter_information.udi_id
     *
     * @param udiId the value for user_barter_information.udi_id
     *
     * @mbg.generated
     */
    public void setUdiId(Integer udiId) {
        this.udiId = udiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_barter_information.uid
     *
     * @return the value of user_barter_information.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_barter_information.uid
     *
     * @param uid the value for user_barter_information.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_barter_information.consignee
     *
     * @return the value of user_barter_information.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_barter_information.consignee
     *
     * @param consignee the value for user_barter_information.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_barter_information.consignee_phone
     *
     * @return the value of user_barter_information.consignee_phone
     *
     * @mbg.generated
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_barter_information.consignee_phone
     *
     * @param consigneePhone the value for user_barter_information.consignee_phone
     *
     * @mbg.generated
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_barter_information.consignee_address
     *
     * @return the value of user_barter_information.consignee_address
     *
     * @mbg.generated
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_barter_information.consignee_address
     *
     * @param consigneeAddress the value for user_barter_information.consignee_address
     *
     * @mbg.generated
     */
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress == null ? null : consigneeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_barter_information.consignee_postalcode
     *
     * @return the value of user_barter_information.consignee_postalcode
     *
     * @mbg.generated
     */
    public Integer getConsigneePostalcode() {
        return consigneePostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_barter_information.consignee_postalcode
     *
     * @param consigneePostalcode the value for user_barter_information.consignee_postalcode
     *
     * @mbg.generated
     */
    public void setConsigneePostalcode(Integer consigneePostalcode) {
        this.consigneePostalcode = consigneePostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBarterUnformation other = (UserBarterUnformation) that;
        return (this.getUdiId() == null ? other.getUdiId() == null : this.getUdiId().equals(other.getUdiId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getConsignee() == null ? other.getConsignee() == null : this.getConsignee().equals(other.getConsignee()))
            && (this.getConsigneePhone() == null ? other.getConsigneePhone() == null : this.getConsigneePhone().equals(other.getConsigneePhone()))
            && (this.getConsigneeAddress() == null ? other.getConsigneeAddress() == null : this.getConsigneeAddress().equals(other.getConsigneeAddress()))
            && (this.getConsigneePostalcode() == null ? other.getConsigneePostalcode() == null : this.getConsigneePostalcode().equals(other.getConsigneePostalcode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUdiId() == null) ? 0 : getUdiId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getConsignee() == null) ? 0 : getConsignee().hashCode());
        result = prime * result + ((getConsigneePhone() == null) ? 0 : getConsigneePhone().hashCode());
        result = prime * result + ((getConsigneeAddress() == null) ? 0 : getConsigneeAddress().hashCode());
        result = prime * result + ((getConsigneePostalcode() == null) ? 0 : getConsigneePostalcode().hashCode());
        return result;
    }
}