package com.daming.bartersystem.entitys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserReviewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_review
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_review
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_review
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public UserReviewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_review
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserReviewIdIsNull() {
            addCriterion("user_review_id is null");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdIsNotNull() {
            addCriterion("user_review_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdEqualTo(Integer value) {
            addCriterion("user_review_id =", value, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdNotEqualTo(Integer value) {
            addCriterion("user_review_id <>", value, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdGreaterThan(Integer value) {
            addCriterion("user_review_id >", value, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_review_id >=", value, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdLessThan(Integer value) {
            addCriterion("user_review_id <", value, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_review_id <=", value, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdIn(List<Integer> values) {
            addCriterion("user_review_id in", values, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdNotIn(List<Integer> values) {
            addCriterion("user_review_id not in", values, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdBetween(Integer value1, Integer value2) {
            addCriterion("user_review_id between", value1, value2, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andUserReviewIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_review_id not between", value1, value2, "userReviewId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdIsNull() {
            addCriterion("review_father_id is null");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdIsNotNull() {
            addCriterion("review_father_id is not null");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdEqualTo(Integer value) {
            addCriterion("review_father_id =", value, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdNotEqualTo(Integer value) {
            addCriterion("review_father_id <>", value, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdGreaterThan(Integer value) {
            addCriterion("review_father_id >", value, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("review_father_id >=", value, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdLessThan(Integer value) {
            addCriterion("review_father_id <", value, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdLessThanOrEqualTo(Integer value) {
            addCriterion("review_father_id <=", value, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdIn(List<Integer> values) {
            addCriterion("review_father_id in", values, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdNotIn(List<Integer> values) {
            addCriterion("review_father_id not in", values, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdBetween(Integer value1, Integer value2) {
            addCriterion("review_father_id between", value1, value2, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewFatherIdNotBetween(Integer value1, Integer value2) {
            addCriterion("review_father_id not between", value1, value2, "reviewFatherId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdIsNull() {
            addCriterion("review_son_id is null");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdIsNotNull() {
            addCriterion("review_son_id is not null");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdEqualTo(Integer value) {
            addCriterion("review_son_id =", value, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdNotEqualTo(Integer value) {
            addCriterion("review_son_id <>", value, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdGreaterThan(Integer value) {
            addCriterion("review_son_id >", value, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("review_son_id >=", value, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdLessThan(Integer value) {
            addCriterion("review_son_id <", value, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdLessThanOrEqualTo(Integer value) {
            addCriterion("review_son_id <=", value, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdIn(List<Integer> values) {
            addCriterion("review_son_id in", values, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdNotIn(List<Integer> values) {
            addCriterion("review_son_id not in", values, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdBetween(Integer value1, Integer value2) {
            addCriterion("review_son_id between", value1, value2, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewSonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("review_son_id not between", value1, value2, "reviewSonId");
            return (Criteria) this;
        }

        public Criteria andReviewTimeIsNull() {
            addCriterion("review_time is null");
            return (Criteria) this;
        }

        public Criteria andReviewTimeIsNotNull() {
            addCriterion("review_time is not null");
            return (Criteria) this;
        }

        public Criteria andReviewTimeEqualTo(Date value) {
            addCriterion("review_time =", value, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeNotEqualTo(Date value) {
            addCriterion("review_time <>", value, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeGreaterThan(Date value) {
            addCriterion("review_time >", value, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("review_time >=", value, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeLessThan(Date value) {
            addCriterion("review_time <", value, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeLessThanOrEqualTo(Date value) {
            addCriterion("review_time <=", value, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeIn(List<Date> values) {
            addCriterion("review_time in", values, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeNotIn(List<Date> values) {
            addCriterion("review_time not in", values, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeBetween(Date value1, Date value2) {
            addCriterion("review_time between", value1, value2, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andReviewTimeNotBetween(Date value1, Date value2) {
            addCriterion("review_time not between", value1, value2, "reviewTime");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_review
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_review
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}