package com.daming.bartersystem.dao;

import com.daming.bartersystem.entitys.BarterOrder;
import com.daming.bartersystem.entitys.BarterOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BarterOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    long countByExample(BarterOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int deleteByExample(BarterOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer barterOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int insert(BarterOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int insertSelective(BarterOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    List<BarterOrder> selectByExample(BarterOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    BarterOrder selectByPrimaryKey(Integer barterOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BarterOrder record, @Param("example") BarterOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BarterOrder record, @Param("example") BarterOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BarterOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BarterOrder record);
}