package com.daming.bartersystem.dao;

import com.daming.bartersystem.entitys.BarterOrderItem;
import com.daming.bartersystem.entitys.BarterOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BarterOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    long countByExample(BarterOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int deleteByExample(BarterOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int insert(BarterOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int insertSelective(BarterOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    List<BarterOrderItem> selectByExample(BarterOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    BarterOrderItem selectByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BarterOrderItem record, @Param("example") BarterOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BarterOrderItem record, @Param("example") BarterOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BarterOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table barter_order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BarterOrderItem record);
}