package com.daming.bartersystem.dao;

import com.daming.bartersystem.entitys.Classification;

import java.util.List;


import com.daming.bartersystem.entitys.ClassificationExample;
import org.apache.ibatis.annotations.Param;

public interface ClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    long countByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int deleteByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer classificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int insert(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int insertSelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    List<Classification> selectByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    Classification selectByPrimaryKey(Integer classificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Classification record);
}