package com.daming.bartersystem.dao;

import com.daming.bartersystem.entitys.ShoppingTrolleyItem;
import java.util.List;

import com.daming.bartersystem.entitys.ShoppingTrolleyItemExample;
import org.apache.ibatis.annotations.Param;

public interface ShoppingTrolleyItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    long countByExample(ShoppingTrolleyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingTrolleyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer trolleyItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int insert(ShoppingTrolleyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingTrolleyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    List<ShoppingTrolleyItem> selectByExample(ShoppingTrolleyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    ShoppingTrolleyItem selectByPrimaryKey(Integer trolleyItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingTrolleyItem record, @Param("example") ShoppingTrolleyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingTrolleyItem record, @Param("example") ShoppingTrolleyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingTrolleyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingTrolleyItem record);
}