package com.daming.bartersystem.dao;

import com.daming.bartersystem.entitys.ShoppingTrolley;
import java.util.List;

import com.daming.bartersystem.entitys.ShoppingTrolleyExample;
import org.apache.ibatis.annotations.Param;

public interface ShoppingTrolleyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    long countByExample(ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer trolleyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int insert(ShoppingTrolley record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingTrolley record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    List<ShoppingTrolley> selectByExample(ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    ShoppingTrolley selectByPrimaryKey(Integer trolleyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingTrolley record, @Param("example") ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingTrolley record, @Param("example") ShoppingTrolleyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingTrolley record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_trolley
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingTrolley record);
}