package com.daming.bartersystem.dao;

import com.daming.bartersystem.entitys.UserBarterUnformation;
import java.util.List;

import com.daming.bartersystem.entitys.UserBarterUnformationExample;
import org.apache.ibatis.annotations.Param;

public interface UserBarterUnformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    long countByExample(UserBarterUnformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int deleteByExample(UserBarterUnformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer udiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int insert(UserBarterUnformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int insertSelective(UserBarterUnformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    List<UserBarterUnformation> selectByExample(UserBarterUnformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    UserBarterUnformation selectByPrimaryKey(Integer udiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBarterUnformation record, @Param("example") UserBarterUnformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBarterUnformation record, @Param("example") UserBarterUnformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBarterUnformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_barter_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBarterUnformation record);
}